/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */
alter table ChatLog drop index `conversaionIndex`;
DROP TABLE IF EXISTS `ChatLog`;

CREATE TABLE `ChatLog` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `fromUserId` VARCHAR(31) NOT NULL,
  `toUserId` VARCHAR(31) NOT NULL,
  `conversaionId` VARCHAR(63) NOT NULL,
  `content` TEXT NOT NULL,
  `time` BIGINT NOT NULL,
  `seq` BIGINT NOT NULL,
  `platform` INT NOT NULL,
  `msgType` INT NOT NULL,
  `groupId` VARCHAR(31) NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `conversaionIndex`
  ON `ChatLog` (
    `conversaionId`,
    `seq`);

