// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "conversation-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // ConversationKey
  //

  bool access::composite_value_traits< ::ConversationKey, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // ownerId_
    //
    if (t[0UL])
    {
      i.ownerId_value.capacity (i.ownerId_size);
      grew = true;
    }

    // conversationId_
    //
    if (t[1UL])
    {
      i.conversationId_value.capacity (i.conversationId_size);
      grew = true;
    }

    return grew;
  }

  void access::composite_value_traits< ::ConversationKey, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (b);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);
    ODB_POTENTIALLY_UNUSED (n);

    // ownerId_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.ownerId_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.ownerId_value.capacity ());
    b[n].length = &i.ownerId_size;
    b[n].is_null = &i.ownerId_null;
    n++;

    // conversationId_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.conversationId_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.conversationId_value.capacity ());
    b[n].length = &i.conversationId_size;
    b[n].is_null = &i.conversationId_null;
    n++;
  }

  bool access::composite_value_traits< ::ConversationKey, id_mysql >::
  init (image_type& i,
        const value_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // ownerId_
    //
    {
      ::std::string const& v =
        o.ownerId_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.ownerId_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.ownerId_value,
        size,
        is_null,
        v);
      i.ownerId_null = is_null;
      i.ownerId_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.ownerId_value.capacity ());
    }

    // conversationId_
    //
    {
      ::std::string const& v =
        o.conversationId_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.conversationId_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.conversationId_value,
        size,
        is_null,
        v);
      i.conversationId_null = is_null;
      i.conversationId_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.conversationId_value.capacity ());
    }

    return grew;
  }

  void access::composite_value_traits< ::ConversationKey, id_mysql >::
  init (value_type& o,
        const image_type&  i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // ownerId_
    //
    {
      ::std::string& v =
        o.ownerId_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.ownerId_value,
        i.ownerId_size,
        i.ownerId_null);
    }

    // conversationId_
    //
    {
      ::std::string& v =
        o.conversationId_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.conversationId_value,
        i.conversationId_size,
        i.conversationId_null);
    }
  }

  // Conversation
  //

  struct access::object_traits_impl< ::Conversation, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::Conversation, id_mysql >::id_type
  access::object_traits_impl< ::Conversation, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      composite_value_traits< ::ConversationKey, id_mysql >::init (
        id,
        i.conversationKey_value,
        db);
    }

    return id;
  }

  bool access::object_traits_impl< ::Conversation, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // conversationKey_
    //
    if (composite_value_traits< ::ConversationKey, id_mysql >::grow (
          i.conversationKey_value, t + 0UL))
      grew = true;

    // conversationType_
    //
    t[2UL] = 0;

    // groupId_
    //
    if (t[3UL])
    {
      i.groupId_value.capacity (i.groupId_size);
      grew = true;
    }

    // toUserId_
    //
    if (t[4UL])
    {
      i.toUserId_value.capacity (i.toUserId_size);
      grew = true;
    }

    // maxSeq_
    //
    t[5UL] = 0;

    // minSeq_
    //
    t[6UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::Conversation, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // conversationKey_
    //
    if (sk != statement_update)
    {
      composite_value_traits< ::ConversationKey, id_mysql >::bind (
        b + n, i.conversationKey_value, sk);
      n += 2UL;
    }

    // conversationType_
    //
    b[n].buffer_type = MYSQL_TYPE_SHORT;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.conversationType_value;
    b[n].is_null = &i.conversationType_null;
    n++;

    // groupId_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.groupId_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.groupId_value.capacity ());
    b[n].length = &i.groupId_size;
    b[n].is_null = &i.groupId_null;
    n++;

    // toUserId_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.toUserId_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.toUserId_value.capacity ());
    b[n].length = &i.toUserId_size;
    b[n].is_null = &i.toUserId_null;
    n++;

    // maxSeq_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.maxSeq_value;
    b[n].is_null = &i.maxSeq_null;
    n++;

    // minSeq_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.minSeq_value;
    b[n].is_null = &i.minSeq_null;
    n++;
  }

  void access::object_traits_impl< ::Conversation, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    mysql::statement_kind sk (mysql::statement_select);
    composite_value_traits< ::ConversationKey, id_mysql >::bind (
      b + n, i.id_value, sk);
  }

  bool access::object_traits_impl< ::Conversation, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // conversationKey_
    //
    if (sk == statement_insert)
    {
      ::ConversationKey const& v =
        o.conversationKey_;

      if (composite_value_traits< ::ConversationKey, id_mysql >::init (
            i.conversationKey_value,
            v,
            sk))
        grew = true;
    }

    // conversationType_
    //
    {
      ::u_short const& v =
        o.conversationType_;

      bool is_null (false);
      mysql::value_traits<
          ::u_short,
          mysql::id_ushort >::set_image (
        i.conversationType_value, is_null, v);
      i.conversationType_null = is_null;
    }

    // groupId_
    //
    {
      ::std::string const& v =
        o.groupId_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.groupId_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.groupId_value,
        size,
        is_null,
        v);
      i.groupId_null = is_null;
      i.groupId_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.groupId_value.capacity ());
    }

    // toUserId_
    //
    {
      ::std::string const& v =
        o.toUserId_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.toUserId_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.toUserId_value,
        size,
        is_null,
        v);
      i.toUserId_null = is_null;
      i.toUserId_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.toUserId_value.capacity ());
    }

    // maxSeq_
    //
    {
      ::uint64 const& v =
        o.maxSeq_;

      bool is_null (false);
      mysql::value_traits<
          ::uint64,
          mysql::id_ulonglong >::set_image (
        i.maxSeq_value, is_null, v);
      i.maxSeq_null = is_null;
    }

    // minSeq_
    //
    {
      ::uint64 const& v =
        o.minSeq_;

      bool is_null (false);
      mysql::value_traits<
          ::uint64,
          mysql::id_ulonglong >::set_image (
        i.minSeq_value, is_null, v);
      i.minSeq_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::Conversation, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // conversationKey_
    //
    {
      ::ConversationKey& v =
        o.conversationKey_;

      composite_value_traits< ::ConversationKey, id_mysql >::init (
        v,
        i.conversationKey_value,
        db);
    }

    // conversationType_
    //
    {
      ::u_short& v =
        o.conversationType_;

      mysql::value_traits<
          ::u_short,
          mysql::id_ushort >::set_value (
        v,
        i.conversationType_value,
        i.conversationType_null);
    }

    // groupId_
    //
    {
      ::std::string& v =
        o.groupId_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.groupId_value,
        i.groupId_size,
        i.groupId_null);
    }

    // toUserId_
    //
    {
      ::std::string& v =
        o.toUserId_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.toUserId_value,
        i.toUserId_size,
        i.toUserId_null);
    }

    // maxSeq_
    //
    {
      ::uint64& v =
        o.maxSeq_;

      mysql::value_traits<
          ::uint64,
          mysql::id_ulonglong >::set_value (
        v,
        i.maxSeq_value,
        i.maxSeq_null);
    }

    // minSeq_
    //
    {
      ::uint64& v =
        o.minSeq_;

      mysql::value_traits<
          ::uint64,
          mysql::id_ulonglong >::set_value (
        v,
        i.minSeq_value,
        i.minSeq_null);
    }
  }

  void access::object_traits_impl< ::Conversation, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    bool grew (false);
    mysql::statement_kind sk (mysql::statement_select);
    {
      if (composite_value_traits< ::ConversationKey, id_mysql >::init (
            i.id_value,
            id,
            sk))
        grew = true;
    }

    if (grew)
      i.version++;
  }

  const char access::object_traits_impl< ::Conversation, id_mysql >::persist_statement[] =
  "INSERT INTO `relation` "
  "(`conversationKey_ownerId`, "
  "`conversationKey_conversationId`, "
  "`conversationType`, "
  "`groupId`, "
  "`toUserId`, "
  "`maxSeq`, "
  "`minSeq`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::Conversation, id_mysql >::find_statement[] =
  "SELECT "
  "`relation`.`conversationKey_ownerId`, "
  "`relation`.`conversationKey_conversationId`, "
  "`relation`.`conversationType`, "
  "`relation`.`groupId`, "
  "`relation`.`toUserId`, "
  "`relation`.`maxSeq`, "
  "`relation`.`minSeq` "
  "FROM `relation` "
  "WHERE `relation`.`conversationKey_ownerId`=? AND `relation`.`conversationKey_conversationId`=?";

  const char access::object_traits_impl< ::Conversation, id_mysql >::update_statement[] =
  "UPDATE `relation` "
  "SET "
  "`conversationType`=?, "
  "`groupId`=?, "
  "`toUserId`=?, "
  "`maxSeq`=?, "
  "`minSeq`=? "
  "WHERE `conversationKey_ownerId`=? AND `conversationKey_conversationId`=?";

  const char access::object_traits_impl< ::Conversation, id_mysql >::erase_statement[] =
  "DELETE FROM `relation` "
  "WHERE `conversationKey_ownerId`=? AND `conversationKey_conversationId`=?";

  const char access::object_traits_impl< ::Conversation, id_mysql >::query_statement[] =
  "SELECT "
  "`relation`.`conversationKey_ownerId`, "
  "`relation`.`conversationKey_conversationId`, "
  "`relation`.`conversationType`, "
  "`relation`.`groupId`, "
  "`relation`.`toUserId`, "
  "`relation`.`maxSeq`, "
  "`relation`.`minSeq` "
  "FROM `relation`";

  const char access::object_traits_impl< ::Conversation, id_mysql >::erase_query_statement[] =
  "DELETE FROM `relation`";

  const char access::object_traits_impl< ::Conversation, id_mysql >::table_name[] =
  "`relation`";

  void access::object_traits_impl< ::Conversation, id_mysql >::
  persist (database& db, const object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::Conversation, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::Conversation, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::Conversation, id_mysql >::pointer_type
  access::object_traits_impl< ::Conversation, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::Conversation, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::Conversation, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::Conversation, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::Conversation, id_mysql >::object_type >
  access::object_traits_impl< ::Conversation, id_mysql >::
  query (database& db, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::Conversation, id_mysql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
