/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `GroupMember`;

DROP TABLE IF EXISTS `Group`;

CREATE TABLE `Group` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `groupName` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `GroupMember` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `roler` ENUM('owner', 'member') NOT NULL,
  `user` BIGINT UNSIGNED NOT NULL,
  `group` BIGINT UNSIGNED NOT NULL
  /*
  CONSTRAINT `GroupMember_group_fk`
    FOREIGN KEY (`group`)
    REFERENCES `Group` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `user_i`
  ON `GroupMember` (`user`);

CREATE INDEX `group_i`
  ON `GroupMember` (`group`);

/*
ALTER TABLE `GroupMember`
  ADD CONSTRAINT `GroupMember_user_fk`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`id`)
*/

